### ISSUE TITLE
change_nun_to_hangeul 테스트 에러 공유

### ISSUE THREAD

**Issue by Hyeonji-Ryu** [LOPES-HUFS/tossi_for_rust#27]
테스트 에러 공유드립니다!

```
fn _change_nun_to_hangeul() {
    let test = "1";
    let result = "일";
    assert_eq!(result, change_nun_to_hangeul(test));
```

**Comment by Hyeonji-Ryu** [comment]
let test = "10010";
    let result = "만십";
    assert_eq!(result, change_num_to_hangeul(test));

새로운 에러 공유 드립니다.

result ) "만일십"

**Comment by dialektike** [comment]
true = [만, 천, 백, 십, 십만, 백만, 천만, 십억, 백억, 천억, ...]
false = [1만, 1천, 1백, 1십, 일십만, 일백만, 일천만, 일십억, 일백억, 일천억,...]

**Comment by dialektike** [comment]
>   ```
> 
>  let test = "100000000";
> 
>  let result = "억";
> 
>  assert_eq!(result, change_nun_to_hangeul(test));
> 
> ```
> 
> 
> 
> as is) "억만"
> 
> to be) "억"

이건 "억"이라고 읽지 않고 "일억"이라고 읽어야 하지 않을까요?

**Comment by dialektike** [comment]
> > ```
> > 
> > let test = "100000000";
> > 
> > let result = "억";
> > 
> > assert_eq!(result, change_nun_to_hangeul(test));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > as is) "억만"
> > to be) "억"
> 
> 
> @Hyeonji-Ryu 이건 "억"이라고 읽지 않고 "일억"이라고 읽어야 하지 않을까요?

이것을 아래 테스트에 추가했습니다.

https://github.com/LOPES-HUFS/tossi_for_rust/blob/0fee81c2ed35ab63e28711675e594986e83694c0/tests/number.rs#L71

**Comment by dialektike** [comment]
> true = [만, 천, 백, 십, 십만, 백만, 천만, 십억, 백억, 천억, ...]
> false = [1만, 1천, 1백, 1십, 일십만, 일백만, 일천만, 일십억, 일백억, 일천억,...]

이 문제는 처리했습니다. 아래 링크 참고하세요.

https://github.com/LOPES-HUFS/tossi_for_rust/commit/0fee81c2ed35ab63e28711675e594986e83694c0

**Comment by dialektike** [comment]
에러를 해결했습니다. 아래 링크 참고하세요.

https://github.com/LOPES-HUFS/tossi_for_rust/commit/d90fdf48807d0d47e92a284798d2da4269752159
