### ISSUE TITLE
종성이 없이 예를 들어 '투' 처럼 입력되었을 때 종성 자리 반환에 대하여

### ISSUE THREAD

**Issue by dialektike** [LOPES-HUFS/tossi_for_rust#7]
종성이 없는 문자, 예를 들어 '투'와 같은 문제를 분리할 때 종성을 `' '` 또는 `''` 어느 것을 처리하는 것이 좋을까요?

현재 참고하고 있는 곳에서는 `''`으로 처리합니다. 아래 링크 참고하세요.

```python
assert split_phonemes(u'투') == (u'ㅌ', u'ㅜ', u'')
```

https://github.com/what-studio/tossi/blob/88bc8523c05fe7b7e23518ee0398ee0a18ba0bc0/test.py#L53

**Comment by Hyeonji-Ryu** [comment]
rust char 타입은 `''`을 지원하지 않아 `' '` 작성하였습니다..!
현재는 종성이 없는 경우 `' '`로 처리합니다.

**Comment by dialektike** [comment]
이 문제에 대해서는 다음과 같은 원칙을 적용해서 해결하고자 합니다.

https://github.com/LOPES-HUFS/tossi_for_rust/wiki#한글-한-글자-처리-원칙
